### ISSUE TITLE
Estrutura do trabalho

### ISSUE THREAD

**Issue by CamilaFreitas** [CamilaFreitas/TDA_Projeto002#2]
Dentre as opções para o projeto dois, sugiro:

Fourier:  para limpeza de ruído
Wavelets: para topologia ou para morfologia

**Comment by arianezarro** [comment]
Ok... tô fazendo a parte de fourier e vc wavelets né (só pra confirmar)?

**Comment by CamilaFreitas** [comment]
Isso :D
