### ISSUE TITLE
Wavelets

### ISSUE THREAD

**Issue by CamilaFreitas** [CamilaFreitas/TDA_Projeto002#3]
Encontrei dois artigos explicando a utilidade de wavelets em para morfologia que achei podem ser bem úteis:

https://www.prl.res.in/~shashi/astro_wavelets/report.pdf
https://www.cambridge.org/core/services/aop-cambridge-core/content/view/S1743921310003029

**Comment by arianezarro** [comment]
vi q vc colocou a estrutura preliminar do codigo mas comenta  ele por favor BASTANTE!!!!

**Comment by arianezarro** [comment]
uma pergunta: o seu codigo vai usar o resultado do meu né?

**Comment by arianezarro** [comment]
a gente vai fazer uma função q engloba as duas funçoes ou vai chamar as duas?

**Comment by CamilaFreitas** [comment]
Vou comentar ainda :) é realmente só preliminar.

É, a ideia era a minha parte usar o output da sua. Então lembra de salvar um arquivo fits de saída hahaha

Eu tava pensando mais em fazer as duas funções separadas, e chamar uma de cada vez. 
Tudo bem ser assim?

**Comment by arianezarro** [comment]
a imagem limpa vai ser gravada como clean _image.fits
Tá ok então

**Comment by arianezarro** [comment]
o codigo das wavelets tá bom... não vi nada de errado não ;)

**Comment by CamilaFreitas** [comment]
Ebaa vou fechar o issue então <3 parte concluída
