### ISSUE TITLE
Fourier

### ISSUE THREAD

**Issue by arianezarro** [CamilaFreitas/TDA_Projeto002#4]
Camila, eu deixei meu código preliminar.... e meu jupyter ou versão de python tem implicância com a ultima parte de salvar o arquivo... tem como vc ver se ele funciona aí? e vê também se vc acha q eu tô fazendo certo hahahahahaah

**Comment by CamilaFreitas** [comment]
Ari, acho que entendi o que pode ser o problema.
Quando você coloca hdr == True, você não está testando se o hdr existe, eu acho que você tá perguntando  pro programa que se os ítens do hdr são verdadeiros...

Acho que uma forma de testar se tem header é perguntar pro usuário na hora de ler a imagem:
hdr = input('A imagem possui header? [True][False]?'), e ai você usa o seu if do final, acho que vai dar certo.

Eu olhei por cima, eu acho que tá certo sim, quando eu chegar em casa a noite eu testo :)

**Comment by arianezarro** [comment]
é mesmo ... foi burrice ... eu esqueci de pensar nessa parte do hdr kkkkkkkk

**Comment by CamilaFreitas** [comment]
Te mandei algumas alterações que eu faria por e-mail, dessa parte de salvar a imagem.

**Comment by arianezarro** [comment]
é bom deixar a parte do if de lado mesmo já q não ta funcionando... vou exigir q a imagem tenha header então

**Comment by arianezarro** [comment]
consegui  fazer rodar o código modificado no meu python (sem o if)

**Comment by arianezarro** [comment]
:)

**Comment by arianezarro** [comment]
o código tá atualizado quando puder dá uma olhada e pode fechar esse issue se quiser
